import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from loguru import logger

from app.models.schemas import AnalysisResult, ReportRequest, ReportResponse, SOAPNote
from app.api.analysis import _result_cache, run_analysis_pipeline

router = APIRouter(prefix="/api/report", tags=["Report"])

_report_cache: dict[str, ReportResponse] = {}


def _generate_soap_note(
    result: AnalysisResult, patient_context: dict | None
) -> SOAPNote:
    f = result.features
    diagnoses_str = ", ".join(d.condition for d in result.diagnoses)

    subjective = "Patient presents for ECG analysis. "
    if patient_context:
        subjective += (
            f"Age: {patient_context.get('age', 'unknown')}, "
            f"Sex: {patient_context.get('sex', 'unknown')}. "
        )
        if patient_context.get("symptoms"):
            subjective += f"Symptoms: {patient_context['symptoms']}. "
    else:
        subjective += "No patient history provided."

    objective_lines = [
        f"Heart Rate: {f.heart_rate:.1f} bpm",
        f"Mean RR Interval: {f.rr_mean:.1f} ms",
        f"RR Std Dev: {f.rr_std:.1f} ms",
        f"HR Variability (SDNN): {f.hr_variability:.2f} ms",
    ]
    if f.rr_rmssd:
        objective_lines.append(f"RMSSD: {f.rr_rmssd:.1f} ms")
    if f.freq_lf_hf_ratio:
        objective_lines.append(f"LF/HF Ratio: {f.freq_lf_hf_ratio:.2f}")
    if f.pr_interval:
        objective_lines.append(f"PR Interval: {f.pr_interval:.1f} ms")
    if f.qrs_duration:
        objective_lines.append(f"QRS Duration: {f.qrs_duration:.1f} ms")
    if f.qt_interval:
        objective_lines.append(f"QT Interval: {f.qt_interval:.1f} ms")
    if f.qtc_interval:
        objective_lines.append(f"QTc (Bazett): {f.qtc_interval:.1f} ms")
    if f.st_segment_deviation is not None:
        objective_lines.append(f"ST Deviation: {f.st_segment_deviation:.2f} mV")
    if f.quality_score is not None:
        objective_lines.append(f"Signal Quality: {f.quality_score:.1f}/100")
    objective = "Extracted ECG metrics:\n" + "\n".join(
        f"  • {line}" for line in objective_lines
    )

    assessment = (
        f"ECG analysis reveals: {diagnoses_str}. "
        f"Overall cardiovascular risk: {result.overall_risk.upper()}. "
    )
    for dx in result.diagnoses:
        assessment += (
            f"\n{dx.condition} (confidence {dx.confidence * 100:.0f}%, {dx.severity}): "
            f"{', '.join(dx.supporting_features[:2])}."
        )

    all_recs: list[str] = []
    for dx in result.diagnoses:
        all_recs.extend(dx.recommendations)
    unique_recs = list(dict.fromkeys(all_recs))
    plan = "Recommended actions:\n" + "\n".join(
        f"  {i + 1}. {r}" for i, r in enumerate(unique_recs[:8])
    )

    return SOAPNote(
        subjective=subjective,
        objective=objective,
        assessment=assessment,
        plan=plan,
    )


def _generate_clinician_summary(result: AnalysisResult) -> str:
    f = result.features
    summary = (
        f"MedQuantum-NIN ECG Analysis Report | Model v{result.model_version} | "
        f"{result.timestamp.strftime('%Y-%m-%d %H:%M UTC')}\n\n"
        f"OVERALL RISK: {result.overall_risk.upper()}\n"
        f"Processing time: {result.processing_time:.0f}ms\n\n"
        f"KEY METRICS:\n"
        f"  HR: {f.heart_rate:.1f} bpm | RR: {f.rr_mean:.1f}±{f.rr_std:.1f} ms | "
        f"HRV: {f.hr_variability:.1f} ms\n"
    )
    if f.rr_rmssd:
        summary += f"  RMSSD: {f.rr_rmssd:.1f} ms"
    if f.freq_lf_hf_ratio:
        summary += f" | LF/HF: {f.freq_lf_hf_ratio:.2f}"
    if f.pr_interval:
        summary += f"  PR: {f.pr_interval:.1f} ms"
    if f.qrs_duration:
        summary += f" | QRS: {f.qrs_duration:.1f} ms"
    if f.qtc_interval:
        summary += f" | QTc: {f.qtc_interval:.1f} ms"
    summary += "\n\nDIFFERENTIAL DIAGNOSIS:\n"
    for i, dx in enumerate(result.diagnoses, 1):
        summary += (
            f"  {i}. {dx.condition} [{dx.severity.upper()}] — "
            f"confidence {dx.confidence * 100:.0f}%\n"
        )
    summary += (
        "\n⚠ This report is generated by AI and requires clinical validation "
        "before any clinical decisions."
    )
    return summary


def _generate_patient_summary(result: AnalysisResult) -> str:
    f = result.features
    hr = f.heart_rate
    risk = result.overall_risk

    if risk == "normal":
        risk_text = "Your heart rhythm looks healthy and regular."
    elif risk == "low-risk":
        risk_text = "Your heart rhythm shows a minor variation that is worth monitoring."
    elif risk == "moderate":
        risk_text = "Your heart rhythm shows some changes that your doctor should review."
    else:
        risk_text = "Your heart rhythm shows changes that need prompt medical attention."

    rr_count = len(result.features.rr_intervals)
    rr_duration = result.features.rr_mean / 1000 * rr_count

    summary = (
        f"Your Heart Health Summary\n\n"
        f"What we measured:\n"
        f"  • Your heart rate: {hr:.0f} beats per minute "
        f"({'within normal range' if 60 <= hr <= 100 else 'outside normal range of 60-100'})\n"
        f"  • We analyzed the timing of your heartbeats over {rr_duration:.0f} seconds\n\n"
        f"What we found:\n"
        f"  {risk_text}\n\n"
        f"What this means for you:\n"
    )

    primary = result.diagnoses[0] if result.diagnoses else None
    if primary:
        if primary.condition == "Normal Sinus Rhythm":
            summary += (
                "  Your heart is beating in a normal, steady rhythm. No action needed.\n"
            )
        elif primary.condition == "Sinus Tachycardia":
            summary += (
                "  Your heart is beating faster than usual. "
                "This can happen with exercise, stress, or caffeine.\n"
            )
        elif primary.condition == "Sinus Bradycardia":
            summary += (
                "  Your heart is beating slower than usual. "
                "Athletes often have slow heart rates naturally.\n"
            )
        else:
            summary += (
                f"  Our analysis detected: {primary.condition}. "
                "Please share this report with your doctor.\n"
            )

    summary += "\nNext steps:\n"
    if result.overall_risk in ("high-risk", "critical"):
        summary += "  ⚠ Please contact your doctor or seek medical care soon.\n"
    else:
        summary += "  ✓ Share this report with your doctor at your next appointment.\n"
    summary += "\n📋 This summary is for information only. Always consult a healthcare professional."
    return summary


@router.post(
    "/generate",
    response_model=ReportResponse,
    summary="Generate full ECG report",
)
async def generate_report(request: ReportRequest):
    """Run analysis and generate complete SOAP note, clinician summary, and patient explanation."""
    try:
        result = await run_analysis_pipeline(request.signal_id)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise HTTPException(500, str(e))

    soap = _generate_soap_note(result, request.patient_context)
    clinician = _generate_clinician_summary(result)
    patient = _generate_patient_summary(result)
    report_id = str(uuid.uuid4())

    response = ReportResponse(
        analysis_result=result,
        patient_context=request.patient_context,
        soap_note=soap,
        clinician_summary=clinician,
        patient_summary=patient,
        generated_at=datetime.now(timezone.utc),
        report_id=report_id,
    )
    _report_cache[report_id] = response
    return response


@router.get(
    "/export/{report_id}",
    response_model=ReportResponse,
    summary="Get report by ID",
)
async def export_report(report_id: str):
    """Retrieve a generated report by its ID."""
    report = _report_cache.get(report_id)
    if not report:
        raise HTTPException(404, f"Report {report_id} not found")
    return report
